### ISSUE TITLE
Pagination active is misleading

### ISSUE THREAD

**Issue by ifirmawan** [satyawikananda/elucidator-blog-starter#5]
![Screen Shot 2021-10-02 at 07 50 49](https://user-images.githubusercontent.com/20871229/135698683-1b33b36d-0f04-4d27-b16f-ab5897150985.png)

Hi @satyawikananda 

Nice to meet you, I'm really excited to contribute to this repo and I'm very happy if i'm able to fix this issue and create new PR.

In my point of view, the active pagination looks like give me an information that i'm currently in second page. But, actually we are in first page.
I think we need to switch the active color or just flip it, from gray to white. How do you think?

Looking forward to working closely with you
Thank you

**Comment by satyawikananda** [comment]
Okay, I agree, you can create a PR to fix this issue :)

**Comment by ifirmawan** [comment]
I'm working on it

**Comment by satyawikananda** [comment]
fixed in #7
