### ISSUE TITLE
Suggest - Create docker container

### ISSUE THREAD

**Issue by ifirmawan** [satyawikananda/elucidator-blog-starter#8]
## Summary
In some case, I've problem to install this apps when I'm using Mac OS without Docker like this
![Screen Shot 2021-10-03 at 12 20 47](https://user-images.githubusercontent.com/20871229/135741020-e64c3ed7-e809-4a7c-a9f9-44612118abf4.png)

We know, if we want to use Vite then Node.js version is **>=12.0.0** as mention at [the official documentation](https://vitejs.dev/guide/#overview)

So, I just doing some experiment to using this apps without upgrading my Node.js version and hopefully everyone can use and install this application in many ways.

Thanks

**Comment by satyawikananda** [comment]
Hi, thank you for your report. Since I built this project using Windows OS, I never get that error, also I don't have any experience with docker 😅. So, it's fine if you want to create a docker container to this starter. I'll check your PR.

**Comment by ifirmawan** [comment]
Ah I see, no worries 😄 . I'm happy to update the readme if you want.

IMHO This app is really awesome and the source code is very clean. So, I just want people not to stop when they are constrained by the environment.

**Comment by satyawikananda** [comment]
Haha thanks :)

**Comment by satyawikananda** [comment]
closed on #9
